### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by CaibinSh** [Novartis/scAR#27]
Hi @fgypas ,

I am making a new release. There are mainly three changes: 1) addition of a readthedocs; 2) code reformatting via black and pylint (pylint now can score >7, so I have increase the standard in the Action test from 0.5 to 6); 3) renaming 'scAR' to 'scar'. 

I have a couple of questions regarding whether these changes influence the bioconda recipe.

- **Will renaming package name (scAR) require modification in bioconda PR?**
All uppercase ('scAR') is changed to lowercase ('scar') in everywhere possible (inc. folder, environment, and etc.) But the repo name may stay as 'scAR' for a while, as renaming repo name requires permission from Nick. 

- **Should we exclude the folder of datasets in the conda recipe?**
In addition, a folder, named 'datasets' contains >100 MBs data is added for the tutorial. Should we exclude it?

**Comment by fgypas** [comment]
@CaibinSh 

>Will renaming package name (scAR) require modification in bioconda PR?
No, I don't think we will have any issue with the bioconda deployment. It's already lowercase there.

> Should we exclude the folder of datasets in the conda recipe?
In general it's not a good practice to add big files. Maybe a solution would be to add these files though git-lfs (https://git-lfs.github.com/). @Tobias-Ternent Do you have any other suggestion?

**Comment by CaibinSh** [comment]
Thanks @fgypas .

Great that there is no influence from renaming.

Regarding these questions, I had a brief conversation with @Tobias-Ternent  in the afternoon. He thinks you are the best expert in this.

git-lfs seems to specialise in uploading big files rather than excluding big files. Fow now, I just move back bigs files to a separate repository (CaibinSh/scAR-Reproducibility). 

All is good now. 

Thanks very much.

**Comment by Tobias-Ternent** [comment]
Hi @fgypas and @CaibinSh , I agree that for those larger files, using git-lfs would be best, that would be following best practices (and speed up checking out the codebase too). It should be very easy to configure, and we can erase the existing files from the git history as well (so they're not directly held in the repo for forever).
