### ISSUE TITLE
BiocondaBot not triggered

### ISSUE THREAD

**Issue by CaibinSh** [Novartis/scar#52]
Hi @fgypas , I made a new release v0.4.1 but bioconda somehow is not triggered upon the new release.

In the new release, some codes related to building process have been refactored. 

- All information in setup.py (deleted) is integrated into setup.cfg. 
- An extra pyproject.toml file is added. 

I am wondering whether these affect the [bioconda-recipes](https://github.com/bioconda/bioconda-recipes).

Many thanks, Caibin

**Comment by fgypas** [comment]
Hi @CaibinSh.  I think the issue is that the name of the repository changed from scAR to scar. I will open a PR to bioconda to fix this.

**Comment by CaibinSh** [comment]
Thanks a lot! @fgypas. This makes sense then. Would we also need to manually make a PR for v0.4.1 as well?

**Comment by fgypas** [comment]
@CaibinSh PR opened: https://github.com/bioconda/bioconda-recipes/pull/34985 including the 0.4.1 update

**Comment by CaibinSh** [comment]
Thanks! @fgypas . Will close this issue now.

**Comment by CaibinSh** [comment]
Hello @fgypas , sorry to bother you again. The BiocondaBot somehow still ignores the new version of scar. Could you give a check or instruct me how to fix it, please? Thanks very much. Caibin

PS. The new version doesn't include any changes related to building, I only add an extra functionality and update the documentations.

**Comment by fgypas** [comment]
Hi @CaibinSh 
I think it's working fine: https://github.com/bioconda/bioconda-recipes/pull/35244
Maybe it took some time to be triggered?
