### ISSUE TITLE
Implementation in scvi-tools

### ISSUE THREAD

**Issue by ricomnl** [Novartis/scar#58]
Hi scAR team,

I'm reaching out to gauge interest in having a mirror implementation in scvi-tools for scAR. Given the existing infrastructure in the scvi-tools repository, I was able to create a port of scAR quite easily as an external module. Of course, the implementation will link to this repository as the original and cites the paper in the docs. 
On top of that, the port would allow users of scvi-tools to use the pretrained scAR encoder for doublet detection using the [solo model](https://docs.scvi-tools.org/en/stable/api/reference/scvi.external.SOLO.html#scvi.external.SOLO).

Here's the pending pull request so you can check out what it would look like in the final implementation: https://github.com/scverse/scvi-tools/pull/1683

Please let me know what you think!

**Comment by CaibinSh** [comment]
Hi @ricomnl ,

Thanks for your interest in scAR. scAR is an open source software. We developed it to improve the data quality and reduce the cost (in turn in some case) for single cell (multi)-omics experiments. We are certainly happy to see that scAR is useful for single-cell community.

Please feel free to let me know when you need help.

Best, Caibin

**Comment by ricomnl** [comment]
This has been merged with: https://github.com/scverse/scvi-tools/commit/2772a09177d4f57be7d6af655f272876af5141af
