### ISSUE TITLE
Sparsity values for mRNA decontamination?

### ISSUE THREAD

**Issue by cnk113** [Novartis/scar#59]
Hello,

I was wondering what the recommendations for the sparsity value would be in denoising mRNA? Specifically if we don't know too much of the data besides UMI/nGenes in the cells etc.? I noticed its generally set at 1 for sgRNA decontamination, but what would the general recommended value be for mRNA?

Thanks,
Chang

**Comment by CaibinSh** [comment]
Hi @cnk113 ,

Thanks for your question. It depends on the number of features. If you use the highly variable genes -- e.g., you delete most of sparse genes and keep several thousands highly variable genes -- a sparsity parameter between 0.6-0.7 would be recommended; if you use the entire gene list (e.g., above 13k), 0.7-0.8 would be recommended; if you use specie-combining genome reference, 0.8-0.9 would be recommended as the data is expected to be highly sparse in this case.

Best,
Caibin

**Comment by CaibinSh** [comment]
Hey @cnk113 , this is a kind of followup question. I was wondering how scAR works for your sgRNA assignment. Are the results satisfying? 
Best, Caibin
