### ISSUE TITLE
Fine tuning guide assignment 

### ISSUE THREAD

**Issue by kvshams** [Novartis/scar#62]
Thank you for the great tool and documentation.

For the guide assignment workflow: 

1.  Are there any limitations/overfitting issues in using the profile estimate implemented in

``` 
setup_anndata(
    adata = PBMC_filtered,
    raw_adata = PBMC_raw,
    prob = 0.7, # try a lower prob value when error ocurs
    min_raw_counts=2,
    kneeplot = True
)
PBMC_filtered.uns["ambient_profile_Antibody Capture"]
```
over
 
```
cell_free_sgRNAs = A549_30K_sgRNA_raw.loc[A549_30K_sgRNA_raw.index.difference(A549_30K_sgRNAs_filtered.index)]
ambient_profile_sgRNAs = cell_free_sgRNAs.sum()/cell_free_sgRNAs.sum().sum()   # pandas.Series
ambient_profile_sgRNAs = ambient_profile_sgRNAs.to_frame("ambient profile")
```
2. How the cutoff in `sgRNAs.inference()` is determined? Are there any factors to assess this cutoff (especially processing multiple samples through loops)

3. Is #46 applicable to the guide assignment for determining the parameters?

Thanks,
Shams

**Comment by CaibinSh** [comment]
Hi Shams,

Thanks for reaching out.

1, For sgRNA assignment, there should be any big differences between these two methods.  In our test, ambient sgRNA counts are highly corrected between cells, empty droplets, and 'shallow' droplets. Using either of them to estimate the ambient profile is fine.

2, We use Bayes factors to determine whether the sgRNA counts are really integrated signal or ambient signal. The default cutoff 3 is a conventional cutoff in Bayes factor. You may see this in multiple research articles (e.g.
https://www.nature.com/articles/s41593-020-0660-4 and https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-020-00980-6)

3, Yes. 400 epochs + 64 mini_batch work well in all my test. However, data can be different between different labs. To identify the best parameters for your experiments, you can run it multiple times with different parameters, check whether the assignments are correlated, use the parameters which lead to the most consistent results.

Hopefully, it helps. Let me know if you have more questions.
Best,
Caibin

**Comment by kvshams** [comment]
Thanks @CaibinSh for the quick responds. This helps.
