### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by hanhuajun40** [Novartis/scar#64]
I used 'conda install -c bioconda scar' command to install scar package. Currently I only can install version 0.2.2 due to conflict. When I load package, 'from scar import model' would show error. Instead, 'from scAR import model' will be fine. However, when I rund the script: sgRNAs = model(raw_count = A549_30K_sgRNAs_filtered, ambient_profile = ambient_profile_sgRNAs, 
               feature_type = 'sgRNAs'), following your tutorial, it shows the error message: TypeError: model.__init__() got an unexpected keyword argument 'ambient_profile'. Can you troubleshoot my case. It is so weird that I cannot follow your tutorial. Thanks!

**Comment by CaibinSh** [comment]
Hi @hanhuajun40 , thanks for your feedback. I would recommend the current version over version 0.2.x. The tutorial is for the recent versions.

Could you tell me the error message of the conflict? It is a bit weird. We have tested it and it works fine.

**Comment by hanhuajun40** [comment]
Hi @CaibinSh , thansk for your comment. Once I updated the acAR to version 0.5.1, it will work as tutorial shows. Very appreciated!
