### ISSUE TITLE
sgRNA assignment

### ISSUE THREAD

**Issue by hanhuajun40** [Novartis/scar#66]
Hi, SCAR team,

Thanks for sharing this handful tool to remove ambient RNAs. I am curious whether your tool can work for dual-sgRNA perturbseq. That means that each cell will receive two sgRNAs against the same gene. Current tutorial seems that the default is only one sgRNA detected, and will take another gRNA as confounding factor, which will over-correct background and remove the biological signal. If the tool still works for dual-sgRNA assignment, how can I set up the parameters. Thanks so much.

Best,
Huajun

**Comment by CaibinSh** [comment]
Hi @hanhuajun40 ,

Thanks for your interest. 

> I am curious whether your tool can work for dual-sgRNA perturbseq. 

Yes, in the tutorial (shown below) you may notice that most cells have a single sgRNA, while only a few have dual sgRNAs (as it is a single sgRNA Perturb-seq). However, if you perform dual-sgRNA Perturb-seq, you should see a higher frequency of cells with 2 sgRNAs. The "cutoff" parameter in the sgRNAs.inference() function can be adjusted to obtain optimal results. If you have any further questions, please don't hesitate to ask. Hope this helps.

Best, Caibin


<img width="569" alt="image" src="https://github.com/Novartis/scar/assets/43896555/83261dd4-d7d0-444a-82a7-5e3e9cd6d256">

**Comment by hanhuajun40** [comment]
Hi, Caibin,

Thanks for your immediate reply as always. If it is supposed to work for dual-sgRNA perturbseq (as described in PMID: 35688146)), it seems that the result is not optimal at my hands. I run scar for my screen result, and used cutoff for 1, 3, and 10 for reference. The result all showed that >90% of cells had single guide. I tested the knockdown efficiency based on scar output, but the knockdown efficiency is very low, while the cell ranger output indicates only ~20% of cells are single guide, but the knockdown efficiency is very high for cell ranger. In reality, if the cells are detected single guide, it is supposed to be two sgRNAs in the cells. It has a chance that only one guide is detected even though it is expressed two guides due to dropout. Therefore, I am sending this ticket to ask you whether scar works for dual-sgRNA screen. My result suggests that scar may not work, especially for the unbalanced expression of dual sgRNAs (for instance one sgRNA expression is 5 fold higher than the other). Is it possible that scar takes the lower expression of sgRNA as background, which is actually biological signal, causing over-correction of background. Thanks!

Best,

**Comment by CaibinSh** [comment]
Thanks for your quick comments. 

This is quite intriguing! While attempting to test the data from PMID: 35688146 last year, I found that the data was preprocessed with sgRNAs already assigned. Can you recommend any other dual-sgRNA Perturb-seq datasets that are available for me to use to test and optimize scAR? I would very much appreciate.

Best,
Caibin

**Comment by hanhuajun40** [comment]
Hi, Caibin,

You may consider these papers PMID: 32231336 or PMID: 36550277. Thanks!

Best,
Huajun

**Comment by CaibinSh** [comment]
thanks a lot, Huajun. 
I will have a check.

Have a nice weekend.
Caibin
