### ISSUE TITLE
Version 0.5.2 ImportError caused by pandas/numpy conflict

### ISSUE THREAD

**Issue by recursivelymanan** [Novartis/scar#68]
Thanks for this wonderful tool! I'm hoping I can get started using it, but I'm running into an issue. I installed through `conda ` using `conda install -c bioconda scar` as instructed in the docs, and the installation went normally. Upon trying to import scar, I get the following error message:

```
ImportError: this version of pandas is incompatible with numpy < 1.22.4
your numpy version is 1.21.0.
Please upgrade numpy to >= 1.22.4 to use this pandas version
```

It seems like installing scar resulted in installation of `pandas=2.2.2` and `numpy=1.21.0`. Any attempts to force a change in the version of pandas or numpy means that scar must also be downgraded, often to `scar=0.4.3`. 

Is there any workaround? I tried using earlier versions of scar for my analysis, but since the docs are all based on version 0.5.2, it was causing me a lot of issues.

Thanks!

**Comment by CaibinSh** [comment]
Thanks for your interest and reporting this issue. @recursivelymanan 

It was an issue between NumPy and pandas in earlier versions of Python. We now require Python version >=3.10 instead of >=3.8.6. The new version, scar 0.5.3, should work now. It may take a couple of days to update on Anaconda, but you can use the following method to install it for now.
```
git clone https://github.com/Novartis/scar.git    
cd scar   
pip install .  
```

**Comment by recursivelymanan** [comment]
Thank you!

**Comment by CaibinSh** [comment]
Thanks for closing this thread up. @recursivelymanan . Just want to let you know that it works now using the following method to install,
```
conda install bioconda::scar
```

Please note that there are no differences in performance between 0.5.2, 0.5.3 and 0.5.4. Only slight improvements are involved.
