### ISSUE TITLE
Compatibility issue with scipy>=1.14

### ISSUE THREAD

**Issue by yalayoubi** [Novartis/scar#78]
Hi,
I am getting an error when running `setup_anndata` function with newer scipy version (>=1.14):
`AttributeError: 'SparseCSRView' object has no attribute 'A'`
this is due to deprecation of `csr_matrix.A` attribute in `scipy 1.13` as it was replaced by `.toarray()` or `.todense()`. 
Is there a plan to update the function to be compatible with newer scipy versions?

**Comment by CaibinSh** [comment]
Hi @yalayoubi , thanks for reporting this issue. I have refactored the code to be compatible with the new version of scipy. The main branch should work for both scipy 1.13.x and 1.14.x now. We will push our new release 0.6.1 and conda package soon. For now, please git clone + pip install.

Best, Caibin
