### ISSUE TITLE
Logging bug when GPU is available it logs CPU is available when training model

### ISSUE THREAD

**Issue by LucHendriks** [Novartis/scar#80]
In the code for the training of the model there is a selection of the device used for torch and I think within the logging there is currently a mistake that if the GPU is present, checked by `torch.cuda.is_available():`, that it logs that CPU is present and will be used.

https://github.com/Novartis/scar/blob/79805f53a3201de91d8b4d5d022c204f320f7c35/scar/main/_scar.py#L225-L227

**Comment by CaibinSh** [comment]
Hi @LucHendriks , thanks very much for your contribution. 
The logging message has been corrected in the commit https://github.com/Novartis/scar/commit/08f9e221a81065e4cf6fbb91821108395d53df21. 
It will be implemented since next version 0.6.1.
